### ISSUE TITLE
Possible server crash from BuildInfo+Air vents

### ISSUE THREAD

**Issue by kontu** [THDigi/BuildInfo#2]
Had a player who accidentally set up infinite looping venting decompression+compression in their grid, for some reason when they went to use the find leak button it seemed to crash the server. Unfortunately this is just a gathering of timeline events and I have not had the time to sit down and reproduce fully myself -- however this may server as a "heads up" should others see it to be sure if it's buildinfo or not I suppose

```
09:13:19.0728 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEMechanic.SEM_MechanicalBlockController.TerminalControls_CustomActionGetter(IMyTerminalBlock block, List`1 actions)
   at Sandbox.Game.Gui.MyTerminalControls.GetActions(IMyTerminalBlock block)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.GetActions(Nullable`1 type)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.get_AllActions()
   at Sandbox.Game.Screens.Helpers.MyToolbarItemActions.GetActionOrNull(String id)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.Update(MyEntity owner, Int64 playerID)
   at Sandbox.Game.Screens.Helpers.MyToolbar.UpdateItem(Int32 index)
   at Sandbox.Game.Screens.Helpers.MyToolbar.SetItemAtIndexInternal(Int32 i, MyToolbarItem item, Boolean initialization, Boolean gamepad)
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.ExecuteAction(MyToolbarItem action)
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.UpdateActions()
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.UpdateAfterSimulation100()
   at Patched_Sandbox.Game.Entities.MyParallelEntityUpdateOrchestratorUpdateAfterSimulation100_0(Object )
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 300
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at SEMechanic.SEM_MechanicalBlockController.TerminalControls_CustomActionGetter(IMyTerminalBlock block, List`1 actions)
   at Sandbox.Game.Gui.MyTerminalControls.GetActions(IMyTerminalBlock block)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.GetActions(Nullable`1 type)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.get_AllActions()
   at Sandbox.Game.Screens.Helpers.MyToolbarItemActions.GetActionOrNull(String id)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalBlock.Update(MyEntity owner, Int64 playerID)
   at Sandbox.Game.Screens.Helpers.MyToolbar.UpdateItem(Int32 index)
   at Sandbox.Game.Screens.Helpers.MyToolbar.SetItemAtIndexInternal(Int32 i, MyToolbarItem item, Boolean initialization, Boolean gamepad)
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.ExecuteAction(MyToolbarItem action)
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.UpdateActions()
   at SpaceEngineers.Game.Entities.Blocks.MyAirVent.UpdateAfterSimulation100()
   at Patched_Sandbox.Game.Entities.MyParallelEntityUpdateOrchestratorUpdateAfterSimulation100_0(Object )
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 300
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
09:13:19.0728 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\SENDS05\Instance\Minidump.dmp
09:13:19.0728 [ERROR]  Initializer: Keen broke the minidump, sorry.

```

**Comment by kontu** [comment]
Blech I don't think you actually touch on  SEMechanic.SEM_MechanicalBlockController that might be mechanical keybinds and they might have found some weird way to bind a key....

yea its mechanical keybinds sorry
